apiVersion: v1
kind: Pod
metadata:
  name: pod-without-label
spec:
  restartPolicy: OnFailure
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo I am running as user $(id -u)"]
